project:
  type: website
  output-dir: _site

website:
  title: "vast-challenge2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Proposal
      - href: poster.qmd
        text: Poster
      - href: about.qmd
        text: About
    right:
      - text: "Shiny App ↗"
        href: https://isss608group5.shinyapps.io/vast-challenge2026/
        target: _blank

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
