project:
  type: website
  output-dir: _site

website:
  title: "vast-challenge2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Proposal
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
